name: Docker Build & Push

on: [push]

jobs:
  build:
    name: docker build and push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Push
        env:
          ECR: ${{ steps.login-ecr.outputs.registry }}
          # TAG: ${{ github.sha }}
          TAG: khs_tag
        run: docker buildx build --push --platform linux/arm64/v8,linux/amd64 -t ${ECR}/khs_base:latest -t ${ECR}/khs_base:${TAG} .
